export type TTrack = {
  positionTrack?: number;
  play?: boolean;
  id: string;
  name?: string;
  duration?: number | string;
  artist_id?: string;
  artist_name?: string;
  artist_idstr?: string;
  album_name?: string;
  album_id?: string;
  license_ccurl?: string;
  position?: number;
  releasedate?: string;
  album_image?: string;
  audio?: string;
  audiodownload?: string;
  prourl?: string;
  shorturl?: string;
  shareurl?: string;
};
